# Generated by Django 6.0.1 on 2026-02-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckInBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=13)),
                ("book_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=300)),
                ("edition_format", models.CharField(max_length=30)),
                ("edition_id", models.CharField(max_length=20)),
                ("insert_dt", models.DateField()),
            ],
        ),
    ]
